services:
  app:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/project
    networks:
      - app-network
    environment:
      - XDEBUG_MODE=debug
      - DATABASE_URL=mysql://root@mysql:3306/laravel_db
    ports:
      - "9001:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mysql:
        condition: service_healthy
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./app/public:/var/www/project/public:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_INNODB_BUFFER_POOL_SIZE: 512M
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_HOST: '%'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --bind-address=0.0.0.0
      - --skip-name-resolve
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--user=root", "--silent" ]
      interval: 10s
      timeout: 45s
      retries: 25
      start_period: 15s
volumes:
  mysql_data:
networks:
  app-network:
    driver: bridge